export const SUGGESTED_QUESTIONS = [
    "Co zawiera Spravato?",
    "Jak działa Milupa?",
    "Czy można stosować Polopiryna Gardo spray w ciąży?",
    "Jaka jest dawka Poltram Retard?",
    "Kiedy stosować Romazic?",
    "Kiedy nie stosować Seretide Dysk?",
    "Jakie jest dawkowanie Neo?",
    "Jakie równoległe preparaty są podobne do Pulnozin?",
    "Kiedy zachować szczególną ostrożność przy stosowaniu Produodopa?",
    "Co zawiera Nutriflex Peri?",
    "Jak działa No?",
    "Czy można stosować Sorafenib Stada w ciąży?",
    "Jaka jest dawka Mixtard?",
    "Kiedy stosować Lipitrop?",
    "Kiedy nie stosować Sinulan Forte Junior?",
    "Jakie jest dawkowanie Lacrimal Natura Plus?",
    "Jakie równoległe preparaty są podobne do Metex?",
    "Kiedy zachować szczególną ostrożność przy stosowaniu Ranivisio?",
    "Co zawiera Mononit 20?",
    "Jak działa Witamina C 1000?",
    "Czy można stosować Intractum Hyperici Phytopharm w ciąży?",
    "Jaka jest dawka Hiconcil Combi?",
    "Kiedy stosować Vallucaps?",
    "Kiedy nie stosować Lecytyna 1200",
    "Jakie jest dawkowanie Olfen?",
    "Jakie równoległe preparaty są podobne do Sonoxen?",
    "Kiedy zachować szczególną ostrożność przy stosowaniu Salbutamol WZF?",
    "Co zawiera Olanzapina Viatris Olanzapina Mylan?",
    "Jak działa Rivel?",
    "Czy można stosować Hascovir Lipozel w ciąży?",
    "Jaka jest dawka Vitis GG?",
    "Kiedy stosować VivaChek Ino?",
    "Kiedy nie stosować KinonD3?",
    "Jakie jest dawkowanie Masc propolisowa 3 z cholesterolem?",
    "Jakie równoległe preparaty są podobne do Syrop prawoslazowo?",
    "Kiedy zachować szczególną ostrożność przy stosowaniu Gaviscon o smaku miety?",
    "Co zawiera Loperamid APTEO MED?",
    "Jak działa Paracetamol Farmina?",
    "Czy można stosować Pelavo Multi 3 w ciąży?",
    "Jaka jest dawka LactoDr?",
    "Kiedy stosować Sinora?",
    "Kiedy nie stosować Nervosed?",
    "Jakie jest dawkowanie Pentohexal 600 Retard?",
    "Jakie równoległe preparaty są podobne do Nervinex?",
    "Kiedy zachować szczególną ostrożność przy stosowaniu Terlipressini acetas EVER Pharma?",
    "Co zawiera Tracrium?",
    "Jak działa Lexapro?",
    "Czy można stosować Olej z nasion wiesioka fit w ciąży?",
    "Jaka jest dawka Paranit?",
    "Kiedy stosować Posterisan?"
]



export const getRandomQuestions = (count: number = 3): string[] => {
  const shuffled = [...SUGGESTED_QUESTIONS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};
